/*
 * Basic API
 *
 * Basic API template
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"net/http"
)

// SystemApiService is a service that implements the logic for the SystemApiServicer
// This service should implement the business logic for every endpoint for the SystemApi API.
// Include any external packages or services that will be required by this service.
type SystemApiService struct {
}

// NewSystemApiService creates a default api service
func NewSystemApiService() SystemApiServicer {
	return &SystemApiService{}
}

// GetHealth - Healthcheck
func (s *SystemApiService) GetHealth(ctx context.Context) (ImplResponse, error) {
	return Response(http.StatusNotImplemented, nil), nil
}
