openapi: 3.0.3
info:
  title: Users API
  description: Users basic CRUD (create, read, update and delete)
  version: v1.0.0
  x-service: users-service
  contact:
    email: rcebrian@github.com
  license:
    name: 'MIT'
    url: https://opensource.org/licenses/MIT
servers:
  - url: 'http://localhost:8080'
    description: localhost environment
tags:
  - name: users
    description: Users use cases
paths:
  /users:
    get:
      tags:
        - users
      operationId: getAllUsers
      summary: Get all users
      description: Retrieve all users from data storage
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/user-dto'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      summary: Create user
      operationId: createUser
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
        '500':
          description: Internal Server Error
      description: Save user into data storage
      requestBody:
        description: Required data to register a new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user-dto'
      tags:
        - users
  '/users/{userId}':
    get:
      summary: Get user by id
      tags:
        - users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user-dto'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: getUserById
      description: Retrieve user information from ID
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: Numeric ID of the user to get
components:
  schemas:
    user-dto:
      title: UserDto
      type: object
      description: 'Entity that represents an user'
      properties:
        id:
          type: string
          example: e8c58bf5-532d-458b-8c6d-b2f828f48b6c
        name:
          type: string
          example: John
        firstname:
          type: string
          example: Doe
